# Generated by Django 3.0.6 on 2020-09-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ensembltestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnsemblTestModel',
        ),
    ]
