# Generated by Django 3.0.6 on 2020-09-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mutation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mutation',
        ),
    ]
