# Generated by Django 3.0.6 on 2020-09-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_mutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvs', models.CharField(max_length=50)),
                ('gene_symbol', models.CharField(max_length=20)),
                ('amino_acid_from', models.CharField(max_length=5)),
                ('amino_acid_to', models.CharField(max_length=5)),
                ('sift_prediction', models.CharField(max_length=20)),
                ('polyphen_prediction', models.CharField(max_length=20)),
                ('sift_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('polyphen_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unified_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MutationGroup')),
            ],
        ),
    ]
