# Generated by Django 3.0.6 on 2020-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mutation_mutationgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='polyphen_prediction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='polyphen_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='sift_prediction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='sift_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='unified_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
