# Generated by Django 3.0.6 on 2020-09-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200914_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crop_type', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=200)),
                ('date_of_opening', models.DateField()),
                ('has_automatic_irrigation', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Farm')),
            ],
        ),
    ]
