# Generated by Django 3.0.6 on 2020-10-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_farm_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genes', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date_time', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='group',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='MutationGroup',
        ),
        migrations.AddField(
            model_name='mutation',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.MutationBatch'),
            preserve_default=False,
        ),
    ]
