# Generated by Django 3.0.6 on 2020-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201014_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='ensembl_id',
            field=models.CharField(default='TEST', max_length=20),
            preserve_default=False,
        ),
    ]
