# Generated by Django 3.0.6 on 2020-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mutation_ensembl_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutationbatch',
            old_name='date_time',
            new_name='creation_datetime',
        ),
        migrations.AddField(
            model_name='mutation',
            name='modification_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
