# Generated by Django 3.0.6 on 2020-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201021_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='polyphen_prediction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='sift_prediction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
