# Generated by Django 3.0.6 on 2020-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201021_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='cadd_raw',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fathmm_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fathmm_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='grantham_distance',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='lrt_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='lrt_score',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='metasvm_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='metasvm_score',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='mutationassessor_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='mutationassessor_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='mutationtaster_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='mutationtaster_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='mutpred_score',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='provean_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='provean_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='vest4_score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
