# Generated by Django 3.0.6 on 2020-10-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201022_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='grantham_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='unified_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
