# Generated by Django 3.0.6 on 2020-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201022_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='cadd_raw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='lrt_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='metasvm_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutpred_score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
