# Generated by Django 3.0.6 on 2020-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201022_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='cadd_raw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fathmm_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fathmm_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='lrt_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='lrt_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='metasvm_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='metasvm_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutationassessor_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutationassessor_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutationtaster_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutationtaster_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutpred_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='polyphen_prediction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='provean_pred',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='provean_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='sift_prediction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='vest4_score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
