# Generated by Django 3.0.6 on 2020-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201027_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='cds_start',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='impact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
